services:
  app:
    build: .
    ports:
      - "7865:7865"
    restart: always
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/co2bunny
      - PORT=7865
      - host=http://localhost:7865
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: